version: '3.8'

services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  bot:
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/bot
    depends_on:
      - redis

volumes:
    redis_data:
